name: learncast_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^6.0.0

  intl: ^0.20.2

  dio: ^5.9.0

  shared_preferences: ^2.5.3

  go_router: ^17.0.0

  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8

  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  pedantic_mono: ^1.35.0

  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2

  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1

  plugin_platform_interface: ^2.1.8
  video_player_platform_interface: ^6.6.0

flutter:
  uses-material-design: true
